{% set version = "0.46" %}

package:
  name: check-manifest
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/check-manifest/check-manifest-{{ version }}.tar.gz
  sha256: 5895e42a012989bdc51854a02c82c8d6898112a4ab11f2d7878200520b49d428

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - check-manifest = check_manifest:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-build >=0.1
    - setuptools
    - toml

test:
  imports:
    - check_manifest
  commands:
    - pip check
    - check-manifest --help
  requires:
    - pip


about:
  home: https://github.com/mgedmin/check-manifest
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Check MANIFEST.in in a Python source package for completeness

extra:
  recipe-maintainers:
    - hodgsonw
    - ocefpaf
