{% set version = "0.39" %}

package:
  name: check-manifest
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/check-manifest/check-manifest-{{ version }}.tar.gz
  sha256: a4c555f658a7c135b8a22bd26c2e55cfaf5876e4d5962d8c25652f2addd556bc

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - check-manifest = check_manifest:main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools
    - toml

test:
  commands:
    - check-manifest --help

about:
  home: https://github.com/mgedmin/check-manifest
  license: MIT
  license_family: MIT
  license_file: LICENCE.rst
  summary: Check MANIFEST.in in a Python source package for completeness

extra:
  recipe-maintainers:
    - hodgsonw
    - ocefpaf
