travis:
  secure:
    BINSTAR_TOKEN: HWSqdrQP2T1NfVNZrvhJit05pRtT63qA/KDkYsiE7lnEh0ECIg3EHnleHOKnWhEDENyFlk2S2LPE4QX+tj69i03Wu0O48TrEWExh7Txwz0FMHv83Teczk04yod+lyCzQ4h6O1/GaEecLQ4c6T5H1/OAqEDb4aK7DZ7zmmZXTID1KtYTObV4f0yeTtwIaEGOJyntzh6EOXl7EVBN2Up3vfjmvTO79N045xlZiRcfjTta11dR/spp2m5HQufGZXiMtOl/hE6mKFN9vCpcKGQkZXxv9E4v57ZGLzl3hu3jQX2Gy47kVKDMvwFvTEbexhlFedIS8+hdz9p2w2NZzkIpvH0u/UuuShGBfU+FzQCdyyWVPCZw/xnfhlsbSLdHZOaeASsLRYBOavMo4rzx6fChQPaMuYrLZyH84p7NVvo6L+AoKhCIFTOmTbVkkyYT1SS7kf05+aRo52fNzVasQSJ2u+hpFYxcu9/Jv6s6cGQ2sMguXrv0onFV4pxAdXCBcW9XAKCXLQk8sopgIzvCV+aa02ASElOkHL3PSR5amxbewRM+BJQq1LVX6TUsruS4YhrVoQjs/HiRllf4qGeFujG/xUhLR8f4pkPZJ8OYW4IafBloyCT37adLN76/PZdT77fT/WjLxkNKKuhuee2oOa/sbZBmuZXs3PthQfqo+G4a7vwk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
